const { stripLeadingSubPath } = require("@11ty/eleventy/src/TemplatePath")

// VARIABLES: Es como una caja donde guardamos datos. Los tipos de datos que tenemos son strings, numbres, boolean.
//STRINGS: Son bloques de texto y siempre van entre comillas
//FUNCIONES: una función agrupa códigos que podemos ejecutar más adelante.
//ARGUMENTOS:  son las variables que agregamos dentro de los paréntesis de la función
//RETURN: es lo que queremos que retorne de la función
//DECLARACIONES(IF): es la forma de que la funcion verifique si algo es true o false
//VALORES BOOLEANOS: los usamos para identificar si es verdadero o falso.